### ISSUE TITLE
Is this official or community model?

### ISSUE THREAD

**Issue by extra-large-onions** [kijai/ComfyUI-FramerWrapper#2]
(Sorry if dumb question) but is this model official? I can't find anything on https://github.com/aim-uofa/Framer. I assume there's no sketch interpolation.
I have to ask, can you take a look at https://github.com/yihao-meng/AniDoc. Thanks so much for your work!

**Comment by kijai** [comment]
They made the weights public in their huggingface, so they are the official weights. The code basically their huggingface spaces demo code, but updated to support latest diffusers and the usual additions I do to make it usable in ComfyUI. 

AniDoc is already on my to-do list actually!
